// tool/console/src/lib/DocCard.svelte
<script lang="ts">
	import { parse } from 'marked';
	import DocCardEnumTags from './DocCardEnumTags.svelte';
	import DocCardStructFields from './DocCardStructFields.svelte';
	import TerminalIcon from './TerminalIcon.svelte';
	import DOMPurify from 'dompurify';
	import { goto } from '$app/navigation';
	import {
		generateExample,
		generateFnResultExample,
		generateHeaderExample,
		isFnTypeData,
		isHeaderData,
		isUnionTagTypeData,
		type TypeData
	} from '$lib';
	import { page } from '$app/stores';
	import { MsgPactSchema } from './msgpact/index.esm';
	import { onMount } from 'svelte';
	import MonacoEditor from './MonacoEditor.svelte';
	import TypeRef from './TypeRef.svelte';
	import Example from './Example.svelte';
	import MockIcon from './MockIcon.svelte';

	export let entry: TypeData;
	export let msgpactSchema: MsgPactSchema;

	let argumentExampleMonaco: MonacoEditor;

	let showExample: boolean = false;
	let includeErrorsInExample: boolean = false;
	let randomSeed = 1;

	let data = entry.data;
	let schemaKey = entry.name;

	let descriptionDef = entry.doc;
	let descriptionStr = Array.isArray(descriptionDef)
		? descriptionDef.map((l) => l.trim()).join('\n')
		: descriptionDef;
	let markdownHtml = typeof descriptionStr == 'string' ? (parse(descriptionStr) as string) : '';
	let description: string = DOMPurify.sanitize(markdownHtml);
	let nameParts = schemaKey.split('.');

	function applyFunctionToExample() {
		let q = new URLSearchParams($page.url.searchParams.toString());
		q.set('v', 'md');
		q.set('mf', schemaKey);
		goto(`?${q.toString()}#${schemaKey}`);
	}

	function toggleHeaderForExample(header: string, schemaKey: string) {
		console.log(`toggleHeaderForExample`, header, schemaKey);
		let q = new URLSearchParams($page.url.searchParams.toString());
		let existingHeaders = (q.get('mh') ?? '').split(',').filter((h) => h !== '');
		console.log(`existingHeaders`, existingHeaders);
		let newHeaders = existingHeaders.includes(header)
			? existingHeaders.filter((h) => h !== header)
			: [...existingHeaders, header];
		q.set('mh', newHeaders.join(','));
		goto(`?${q.toString()}#${schemaKey}`);
	}

	function toggleShowExample() {
		showExample = !showExample;
	}

	function incrementRandomSeed() {
		randomSeed += 1;
	}

	onMount(() => {
		const hash = $page.url.hash;
		const id = hash?.replace('#', '');
		if (id) {
			if (id == schemaKey) {
				// scroll into view
				document.getElementById(schemaKey)?.scrollIntoView();
			}
		}
	});
</script>

<section
	id={schemaKey}
	aria-label={schemaKey}
	class="mb-2 rounded-lg border border-gray-200 bg-white p-6 shadow dark:border-gray-700 dark:bg-gray-800"
>
	<div class="flex w-full items-center pb-4">
		<a href="#{schemaKey}">
			<h5
				class="rounded-md px-2 py-1 font-mono text-2xl font-bold tracking-tight text-white {schemaKey.startsWith(
					'fn'
				)
					? 'bg-amber-700'
					: schemaKey.startsWith('struct')
						? 'bg-sky-700'
						: schemaKey.startsWith('union')
							? 'bg-green-700'
							: schemaKey.startsWith('errors')
								? 'bg-rose-800'
								: schemaKey.startsWith('info')
									? 'bg-slate-600'
									: 'bg-gray-700'}"
			>
				{schemaKey}
			</h5>
		</a>
		{#if isFnTypeData(data)}
			<span class="grow" />
			<div>
				<button
					on:click={applyFunctionToExample}
					class="group flex items-center space-x-2 py-2"
				>
					<span class="group-hover:underline">Simulate</span>
					<div class="rounded-lg p-1 group-hover:bg-sky-700 group-hover:text-cyan-300">
						<MockIcon />
					</div>
				</button>
			</div>
		{/if}
	</div>
	<div>
		{#if schemaKey.startsWith('struct')}
			<DocCardStructFields fields={entry.data} />
			{#if description}
				<div class="docstring font-normal text-gray-700 dark:text-gray-400">
					{@html description}
				</div>
			{/if}

			<Example {schemaKey} generate={() => generateExample(schemaKey, msgpactSchema)} />
		{:else if isFnTypeData(data)}
			<div class="space-y-1">
				<section aria-label="Arguments">
				<DocCardStructFields fields={data.args} />
				{#if description}
					<div class="docstring font-normal text-gray-700 dark:text-gray-400">
						{@html description}
					</div>
				{/if}

				<Example {schemaKey} generate={() => generateExample(schemaKey, msgpactSchema)} />
				</section>

				<section aria-label="Result">
					<div>
						<span class="text-3xl text-emerald-500">→</span>
					</div>

					<DocCardEnumTags tags={data.results} />

					<div class="flex items-center justify-center space-x-2">
						<button
							aria-label="Result Example"
							on:click={toggleShowExample}
							class="group mt-2 flex items-center rounded-lg hover:underline"
						>
							<h6
								class="rounded-md p-2 {showExample
									? 'border border-slate-500 font-bold'
									: ''}"
							>
								{showExample ? 'Hide' : ''} Example
							</h6>
						</button>
						{#if showExample}
							<button
								on:click={incrementRandomSeed}
								class="group mt-2 flex items-center rounded-lg hover:underline"
							>
								<h6 class="rounded-md border border-slate-500 p-2 font-bold">
									Regenerate
								</h6>
							</button>
							<label>
								<input
									type="checkbox"
									class="mr-1"
									bind:checked={includeErrorsInExample}
								/> Include Errors
							</label>
						{/if}
					</div>
					{#if showExample}
						<div class="py-2">
							{#key randomSeed}
								<MonacoEditor
									id={schemaKey}
									readOnly={true}
									json={generateFnResultExample(
										schemaKey,
										msgpactSchema,
										includeErrorsInExample
											? null
											: {
													Ok_: {}
												},
										!includeErrorsInExample
									)}
									allowLinks={false}
									filename={schemaKey + '.result.json'}
									ariaLabel={schemaKey + '.result.example'}
									fullHeight={false}
									lineNumbers={false}
									minimap={false}
								/>
							{/key}
						</div>
					{/if}

					{#if data.inheritedErrors?.length ?? 0 > 0}
						<div class="pt-4">
							<div class="border-t border-gray-500 pt-2">
								<h6 class="font-bold tracking-tight">Also includes:</h6>
								<ul>
									{#each data.inheritedErrors as inheritedError}
										<ul>
											<a
												href={`#${inheritedError}`}
												class="text-md pl-4 text-sky-400 hover:underline"
												>{inheritedError}</a
											>
										</ul>
									{/each}
								</ul>
							</div>
						</div>
					{/if}
				</section>
			</div>
		{:else if isUnionTagTypeData(data)}
			{#if description}
				<div class="docstring font-normal text-gray-700 dark:text-gray-400">
					{@html description}
				</div>
			{/if}

			<div class="space-y-2">
				<DocCardEnumTags tags={data} />
			</div>

			<Example {schemaKey} generate={() => generateExample(schemaKey, msgpactSchema)} />
		{:else if isHeaderData(data)}
			<div>
				{#if description}
					<div class="docstring font-normal text-gray-700 dark:text-gray-400">
						{@html description}
					</div>
				{/if}

				<DocCardStructFields fields={data.requestData}>
					<div slot="field" let:header>
						<button
							on:click={() => toggleHeaderForExample(header, schemaKey)}
							class="group flex items-center space-x-2"
						>
							<span class="group-hover:underline">Simulate</span>
							<div
								class="rounded-lg px-1 group-hover:bg-sky-700 group-hover:text-cyan-300"
							>
								<MockIcon />
							</div>
						</button>
					</div>
				</DocCardStructFields>

				{#if Object.keys(data.requestData).length > 0}
					<Example
						schemaKey={'request.' + schemaKey}
						generate={() =>
							generateHeaderExample(
								'request',
								Object.keys(data.requestData),
								msgpactSchema
							)}
					/>
				{/if}
				<div class="pl-4">
					<span class="text-3xl text-emerald-500">→</span>
				</div>

				<DocCardStructFields fields={data.responseData} />

				{#if Object.keys(data.responseData).length > 0}
					<Example
						schemaKey={'response.' + schemaKey}
						generate={() =>
							generateHeaderExample(
								'response',
								Object.keys(data.responseData),
								msgpactSchema
							)}
					/>
				{/if}
			</div>
		{:else if description}
			<div class="docstring font-normal text-gray-700 dark:text-gray-400">
				{@html description}
			</div>
		{/if}
	</div>
</section>

// sdk/console/src/components/DocCard.tsx
//|
//|  Copyright The Telepact Authors
//|  SPDX-License-Identifier: Apache-2.0
//|

import { useEffect, useMemo, useState } from 'react';
import DocCardEnumTags from './DocCardEnumTags';
import DocCardStructFields from './DocCardStructFields';
import Example from './Example';
import MonacoEditor from './MonacoEditor';
import TypeRef from './TypeRef';
import MockIcon from './icons/MockIcon';
import {
	generateExample,
	generateFnResultExample,
	generateHeaderExample,
	isFnTypeData,
	isHeaderData,
	isUnionTagTypeData,
	markdownHtml,
	type HeaderData,
	type TypeData
} from '../lib/console';
import type { TelepactSchema } from '../lib/telepact/index.esm.js';

export default function DocCard(props: {
	entry: TypeData;
	telepactSchema: TelepactSchema;
	navigate: (url: string) => void;
}) {
	const { entry, telepactSchema, navigate } = props;

	const schemaKey = entry.name;
	const data = entry.data;

	const description = useMemo(() => markdownHtml(entry as any), [entry]);

	const [showResultExample, setShowResultExample] = useState(false);
	const [includeErrorsInExample, setIncludeErrorsInExample] = useState(false);
	const [randomSeed, setRandomSeed] = useState(1);

	const applyFunctionToExample = () => {
		const q = new URLSearchParams(window.location.search);
		q.set('v', 'md');
		q.set('mf', schemaKey);
		navigate(`?${q.toString()}#${schemaKey}`);
	};

	const toggleHeaderForExample = (header: string) => {
		const q = new URLSearchParams(window.location.search);
		const existingHeaders = (q.get('mh') ?? '')
			.split(',')
			.map((h) => h.trim())
			.filter((h) => h !== '');
		const newHeaders = existingHeaders.includes(header)
			? existingHeaders.filter((h) => h !== header)
			: [...existingHeaders, header];
		q.set('mh', newHeaders.join(','));
		navigate(`?${q.toString()}#${schemaKey}`);
	};

	useEffect(() => {
		const id = window.location.hash?.replace('#', '');
		if (id && id === schemaKey) {
			document.getElementById(schemaKey)?.scrollIntoView();
		}
	}, [schemaKey]);

	const badgeClass = useMemo(() => {
		if (schemaKey.startsWith('fn')) return 'bg-amber-500 dark:bg-amber-700';
		if (schemaKey.startsWith('struct')) return 'bg-sky-500 dark:bg-sky-700';
		if (schemaKey.startsWith('union')) return 'bg-green-500 dark:bg-green-700';
		if (schemaKey.startsWith('errors')) return 'bg-rose-500 dark:bg-rose-800';
		if (schemaKey.startsWith('info')) return 'bg-slate-300 dark:bg-slate-600';
		return 'bg-gray-200 dark:bg-gray-700';
	}, [schemaKey]);

	return (
		<section
			id={schemaKey}
			aria-label={schemaKey}
			className="mb-2 rounded-lg border border-gray-300 bg-white p-6 shadow dark:border-gray-700 dark:bg-gray-800"
		>
			<div className="flex w-full items-center pb-4">
				<a href={`#${schemaKey}`}>
					<h5
						className={`rounded-md px-2 py-1 font-mono text-2xl font-bold tracking-tight text-gray-900 dark:text-white ${badgeClass}`}
					>
						{schemaKey}
					</h5>
				</a>
				{isFnTypeData(data) ? (
					<>
						<span className="grow" />
						<div>
							<button onClick={applyFunctionToExample} className="group flex items-center space-x-2 py-2">
								<span className="group-hover:underline">Simulate</span>
								<div className="rounded-lg p-1 group-hover:bg-sky-700 group-hover:text-cyan-300">
									<MockIcon />
								</div>
							</button>
						</div>
					</>
				) : null}
			</div>

			<div>
				{schemaKey.startsWith('struct') ? (
					<>
						<DocCardStructFields fields={entry.data as Record<string, any>} />
						{description ? (
							<div className="pt-4 prose dark:prose-invert" dangerouslySetInnerHTML={{ __html: description }} />
						) : null}
						<Example schemaKey={schemaKey} generate={() => generateExample(schemaKey, telepactSchema)} />
					</>
				) : isFnTypeData(data) ? (
					<div className="space-y-1">
						<section aria-label="Arguments">
							<DocCardStructFields fields={data.args} />
							{description ? (
								<div
									className="pt-4 prose dark:prose-invert"
									dangerouslySetInnerHTML={{ __html: description }}
								/>
							) : null}
							<Example schemaKey={schemaKey} generate={() => generateExample(schemaKey, telepactSchema)} />
						</section>

						<section aria-label="Result">
							<div>
								<span className="text-3xl text-emerald-500">→</span>
							</div>

							<DocCardEnumTags tags={data.results} />

							<div className="flex items-center justify-center space-x-2">
								<button
									onClick={() => setShowResultExample((v) => !v)}
									className="group mt-2 flex items-center rounded-lg hover:underline"
								>
									<h6
										className={`rounded-md p-2 ${showResultExample ? 'border border-slate-500 font-bold' : ''}`}
									>
										{showResultExample ? 'Hide Example' : 'Example'}
									</h6>
								</button>
								{showResultExample ? (
									<>
										<button
											onClick={() => setRandomSeed((v) => v + 1)}
											className="group mt-2 flex items-center rounded-lg hover:underline"
										>
											<h6 className="rounded-md border border-slate-500 p-2 font-bold">Regenerate</h6>
										</button>
										<label>
											<input
												type="checkbox"
												className="mr-1"
												checked={includeErrorsInExample}
												onChange={(e) => setIncludeErrorsInExample(e.target.checked)}
											/>{' '}
											Include Errors
										</label>
									</>
								) : null}
							</div>

							{showResultExample ? (
								<div className="py-2">
									<MonacoEditor
										key={randomSeed}
										id={schemaKey}
										readOnly={true}
										json={generateFnResultExample(
											schemaKey,
											telepactSchema,
											includeErrorsInExample ? null : { Ok_: {} },
											!includeErrorsInExample
										)}
										allowLinks={false}
										filename={`${schemaKey}.result.json`}
										ariaLabel={`${schemaKey}.result.example`}
										fullHeight={false}
										lineNumbers={false}
										minimap={false}
									/>
								</div>
							) : null}

							{(data.inheritedErrors?.length ?? 0) > 0 ? (
								<div className="pt-4">
									<div className="border-t border-gray-500 pt-2">
										<h6 className="font-bold tracking-tight">Also includes:</h6>
										<ul>
											{data.inheritedErrors.map((inheritedError) => (
												<ul key={inheritedError}>
													<a
														href={`#${inheritedError}`}
														className="text-md pl-4 text-sky-400 hover:underline"
													>
														{inheritedError}
													</a>
												</ul>
											))}
										</ul>
									</div>
								</div>
							) : null}
						</section>
					</div>
				) : isUnionTagTypeData(data) ? (
					<>
						{description ? (
							<div className="pb-2 prose dark:prose-invert" dangerouslySetInnerHTML={{ __html: description }} />
						) : null}
						<div className="space-y-2">
							<DocCardEnumTags tags={data} />
						</div>
						<Example schemaKey={schemaKey} generate={() => generateExample(schemaKey, telepactSchema)} />
					</>
				) : isHeaderData(data) ? (
					<div>
						{description ? (
							<div className="prose dark:prose-invert" dangerouslySetInnerHTML={{ __html: description }} />
						) : null}

						<DocCardStructFields
							fields={(data as HeaderData).requestData}
							field={({ header }) => (
								<button
									onClick={() => toggleHeaderForExample(header)}
									className="group flex items-center space-x-2"
								>
									<span className="group-hover:underline">Simulate</span>
									<div className="rounded-lg px-1 group-hover:bg-sky-700 group-hover:text-cyan-300">
										<MockIcon />
									</div>
								</button>
							)}
						/>

						{Object.keys((data as HeaderData).requestData).length > 0 ? (
							<Example
								schemaKey={`request.${schemaKey}`}
								generate={() =>
									generateHeaderExample('request', Object.keys((data as HeaderData).requestData), telepactSchema)
								}
							/>
						) : null}

						<div className="pl-4">
							<span className="text-3xl text-emerald-500">→</span>
						</div>

						<DocCardStructFields fields={(data as HeaderData).responseData} />

						{Object.keys((data as HeaderData).responseData).length > 0 ? (
							<Example
								schemaKey={`response.${schemaKey}`}
								generate={() =>
									generateHeaderExample('response', Object.keys((data as HeaderData).responseData), telepactSchema)
								}
							/>
						) : null}
					</div>
				) : description ? (
					<div className="prose dark:prose-invert" dangerouslySetInnerHTML={{ __html: description }} />
				) : null}
			</div>
		</section>
	);
}
