// tool/console/src/lib/TypeRef.svelte
<script lang="ts">
	export let types: any[];
	let generics = types.slice(1, types.length);
	let typeName = types[0];
	let nullable = typeName.endsWith('?');
	let cleanTypeName = typeName.replace(/\?$/g, '');
	let displayNameSpit = cleanTypeName.split('.');
	let displayName: string;
	if (displayNameSpit.length === 1) {
		displayName = displayNameSpit[0];
	} else {
		let target = displayNameSpit[1];
		if (isNaN(target)) {
			displayName = target;
		} else {
			displayName = `T${target}`;
		}
	}
	const standardTypes = ['boolean', 'integer', 'number', 'string', 'array', 'object', 'any'];
</script>

<span class="px-0 text-stone-200"
	>{#if standardTypes.includes(cleanTypeName)}<span class="px-0 text-stone-400"
			>{displayName}</span
		>{:else}<a
			href="#{cleanTypeName}"
			class="px-0 hover:underline {cleanTypeName.startsWith('struct')
				? 'text-sky-400'
				: 'text-emerald-500'}">{displayName}</a
		>{/if}{#if generics.length > 0}&lt;{#each generics as generic, i}<svelte:self
				types={generic}
			/>{#if i < generics.length - 1},&#20;{/if}{/each}&gt;{/if}{#if nullable}?{/if}</span
>

// sdk/console/src/components/TypeRef.tsx
//|
//|  Copyright The Telepact Authors
//|  SPDX-License-Identifier: Apache-2.0
//|

const standardTypes = ['boolean', 'integer', 'number', 'string', 'array', 'object', 'any'];

function getTypeInfo(typeData: unknown): { cleanTypeName: string; displayName: string; generics: any | null; nullable: boolean } {
	if (Array.isArray(typeData)) {
		return { cleanTypeName: 'array', displayName: 'array', generics: typeData[0], nullable: false };
	}
	if (typeof typeData === 'object' && typeData !== null) {
		const asRecord = typeData as Record<string, any>;
		return { cleanTypeName: 'object', displayName: 'object', generics: asRecord['string'], nullable: false };
	}

	const typeName = String(typeData);
	const nullable = typeName.endsWith('?');
	const cleanTypeName = typeName.replace(/\?$/g, '');
	const displayTokens = cleanTypeName.split('.');
	const displayName = displayTokens.length === 1 ? displayTokens[0] : displayTokens[1] ?? cleanTypeName;

	return { cleanTypeName, displayName, generics: null, nullable };
}

export default function TypeRef(props: { types: any }) {
	const { cleanTypeName, displayName, generics, nullable } = getTypeInfo(props.types);
	const isStandard = standardTypes.includes(cleanTypeName);

	return (
		<span className="px-0 text-stone-200">
			{isStandard ? (
				<span className="px-0 text-stone-400">{displayName}</span>
			) : (
				<a
					href={`#${cleanTypeName}`}
					className={`px-0 hover:underline ${cleanTypeName.startsWith('struct') ? 'text-sky-400' : 'text-emerald-500'}`}
				>
					{displayName}
				</a>
			)}
			{generics != null ? (
				<>
					&lt;<TypeRef types={generics} />&gt;
				</>
			) : null}
			{nullable ? '?' : null}
		</span>
	);
}
